plugins {
    id 'com.diffplug.spotless' version '7.0.2' apply false
}

subprojects {
    apply plugin: 'com.diffplug.spotless'

    pluginManager.withPlugin('java') {
        apply plugin: 'jacoco'

        jacoco {
            toolVersion = '0.8.12'
        }

        tasks.named('test') {
            finalizedBy jacocoTestReport
        }

        jacocoTestReport {
            dependsOn test
            reports {
                xml.required = true
                html.required = true
                csv.required = false
            }
        }
    }

    spotless {
        java {
            target 'src/**/*.java'
            palantirJavaFormat('2.50.0')
            importOrder('java', 'javax', 'org', 'com', '')
            removeUnusedImports()
            trimTrailingWhitespace()
            endWithNewline()
        }
    }
}
